"""Fix chapter number

Revision ID: 215e41dc810d
Revises: 374e6e52f933
Create Date: 2021-08-01 21:28:49.876275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215e41dc810d'
down_revision = '71a2aeb7d28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'number')
    op.add_column('chapter', sa.Column('number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'number')
    op.add_column('chapter', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
