"""Add scan group to chapter

Revision ID: 27f49b4b1845
Revises: 5364a1d72c53
Create Date: 2021-08-05 19:23:23.228311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f49b4b1845'
down_revision = '5364a1d72c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('scan_group', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'scan_group')
    # ### end Alembic commands ###
