"""Handle upload sessions

Revision ID: 31080335cd7b
Revises: f3a70f6f7132
Create Date: 2021-08-01 20:34:23.362160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31080335cd7b'
down_revision = 'f3a70f6f7132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('length', sa.Integer(), nullable=False))
    op.drop_constraint('chapter_manga_id_fkey', 'chapter', type_='foreignkey')
    op.create_foreign_key(None, 'chapter', 'manga', ['manga_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.create_foreign_key('chapter_manga_id_fkey', 'chapter', 'manga', ['manga_id'], ['id'])
    op.drop_column('chapter', 'length')
    # ### end Alembic commands ###
