"""Create manga model

Revision ID: 5ed03bc34ad9
Revises: 
Create Date: 2021-08-01 14:26:39.156761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ed03bc34ad9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('year', sa.Numeric(precision=4, scale=0), nullable=True),
    sa.Column('status', sa.Enum('ongoing', 'completed', 'hiatus', 'cancelled', name='status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manga')
    # ### end Alembic commands ###
