"""Chapter add upload time

Revision ID: 77c237dc55e4
Revises: f4e41b9181d8
Create Date: 2021-08-02 17:34:39.444127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c237dc55e4'
down_revision = 'f4e41b9181d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('upload_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'upload_time')
    # ### end Alembic commands ###
