"""Allow edit uploads

Revision ID: a5a3e07a92f6
Revises: c1954996eea5
Create Date: 2021-08-03 14:30:38.869520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5a3e07a92f6'
down_revision = 'c1954996eea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadsession', sa.Column('chapter_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'uploadsession', 'chapter', ['chapter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploadsession', type_='foreignkey')
    op.drop_column('uploadsession', 'chapter_id')
    # ### end Alembic commands ###
