"""Change chapter number type

Revision ID: c1954996eea5
Revises: 77c237dc55e4
Create Date: 2021-08-03 14:23:24.232766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1954996eea5'
down_revision = '77c237dc55e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'number')
    op.add_column('chapter', sa.Column('number', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'number')
    op.add_column('chapter', sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
