"""Add webtoon column

Revision ID: ef8e8e359117
Revises: 27f49b4b1845
Create Date: 2021-09-04 10:39:17.773470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8e8e359117'
down_revision = '27f49b4b1845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('webtoon', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'webtoon')
    # ### end Alembic commands ###
