"""Add name to uploaded blob

Revision ID: f4e41b9181d8
Revises: 215e41dc810d
Create Date: 2021-08-02 15:38:08.974691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e41b9181d8'
down_revision = '215e41dc810d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadedblob', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadedblob', 'name')
    # ### end Alembic commands ###
