# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM nginx:1.17 as final-stage
COPY ./nginx.conf /etc/nginx/nginx.conf
WORKDIR /srv
COPY --from=build-stage /app/dist .
RUN mkdir /srv/media