# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install

ARG VUE_APP_DOMAIN_NAME=localhost
ARG VUE_APP_PROTOCOL=http
ENV VUE_APP_DOMAIN_NAME=$VUE_APP_DOMAIN_NAME
ENV VUE_APP_PROTOCOL=$VUE_APP_PROTOCOL


# production stage
FROM build-stage
COPY . .
CMD ["npm", "run", "serve"]
